-- Crear base de datos dbCursos
CREATE DATABASE IF NOT EXISTS dbCursos
DEFAULT CHARACTER SET utf8;

-- Poner en uso la base de datos dbCursos
USE dbCursos;

-- Ver cual es la base de datos en uso
SELECT DATABASE();

/* Crear tablas */

-- Crear tabla PERSONA
CREATE TABLE PERSONA (
    DNIPER char(8),
    NOMPER varchar(50) NOT NULL,
    APEPER varchar(80) NOT NULL,
    FECNACPER date NOT NULL,
    CELPER char(9),
    EMAPER varchar(100),
    SEXPER char(1) NOT NULL,
    TIPPER char(3) NOT NULL,
    DISTPER varchar(80) NOT NULL,
    FECREGPER timestamp,
    PWSPER varchar(20),
    CONSTRAINT DNIPER_PK PRIMARY KEY (DNIPER)
);

-- Crear tabla DEPARTAMENTO
CREATE TABLE DEPARTAMENTO (
    IDDEP int,
    NOMDEP varchar(50) NOT NULL,
    DNIPER char(8),
    SALJEFDEP DECIMAL(8,2),
    CONSTRAINT IDDEP_PK PRIMARY KEY(IDDEP)
);

-- Crear tabla HISTORICO
CREATE TABLE HISTORICO (
    IDHIS int,
    DNIPER varchar(8),
    FECFINHIST date NOT NULL,
    TIPHIS char(3) NOT NULL,
    COMEHIS varchar(100),
    CONSTRAINT IDHIS_PK PRIMARY KEY (IDHIS)
);

-- Crear tabla EMPLEADO
CREATE TABLE EMPLEADO (
    IDEMP int,
    DNIPER char(8),
    FECINGEMP date NOT NULL,
    CARGEMP varchar(40) NOT NULL,
    SALEMP decimal(6,2) NOT NULL,
    IDDEP int,
    ESTEMP char(1),
    CONSTRAINT IDEMP_PK PRIMARY KEY (IDEMP)
);

-- Crear tabla INSCRIPCION
CREATE TABLE INSCRIPCION (
    IDINSC int,
    DNIPER char(8),
    IDEMP int,
    IDOFER int,
    FECINS date NOT NULL,
    EVALINSC int,
    CONSTRAINT IDINSC_PK PRIMARY KEY (IDINSC)
);

-- Crear tabla OFERTA
CREATE TABLE OFERTA (
    IDOFER int,
    CODCUR char(3),
    FECOFER date NOT NULL,
    FECINICCUROFER date NOT NULL,
    IDEMP int,
    CONSTRAINT IDOFER_PK PRIMARY KEY (IDOFER)
);

-- Crear tabla CURSO
CREATE TABLE CURSO (
    CODCUR char(3),
    DESCUR varchar(30) NOT NULL,
    CATCUR char(3) NOT NULL,
    DURCUR int NOT NULL,
    CONSTRAINT CODCUR_PK PRIMARY KEY (CODCUR)
);

-- Listar todas las tablas
SHOW TABLES;

/* Crear las relaciones */

-- Relacionar la tabla PERSONA - DEPARTAMENTO
ALTER TABLE DEPARTAMENTO
ADD CONSTRAINT PERSONA_DEPARTAMENTO_DNIPER
FOREIGN KEY (DNIPER) REFERENCES PERSONA (DNIPER);

-- Relacionar la tabla PERSONA - HISTORICO
ALTER TABLE DEPARTAMENTO
ADD CONSTRAINT PERSONA_HISTORICO_DNIPER
FOREIGN KEY (DNIPER) REFERENCES PERSONA (DNIPER);

-- Relacionar la tabla PERSONA - EMPLEADO
ALTER TABLE EMPLEADO
ADD CONSTRAINT PERSONA_EMPLEADO_DNIPER
FOREIGN KEY (DNIPER) REFERENCES PERSONA (DNIPER);

-- Relacionar la tabla PERSONA - INSCRIPCION
ALTER TABLE INSCRIPCION
ADD CONSTRAINT PERSONA_INSCRIPCION_DNIPER
FOREIGN KEY (DNIPER) REFERENCES PERSONA (DNIPER);

-- Relacionar la tabla DEPARTAMENTO - EMPLEADO
ALTER TABLE EMPLEADO
ADD CONSTRAINT DEPARTAMENTO_EMPLEADO_IDDEP
FOREIGN KEY (IDDEP) REFERENCES DEPARTAMENTO (IDDEP);

-- Relacionar la tabla EMPLEADO - INSCRIPCION
ALTER TABLE INSCRIPCION
ADD CONSTRAINT EMPLEADO_INSCRIPCION_IDEMP
FOREIGN KEY (IDEMP) REFERENCES EMPLEADO (IDEMP);

-- Relacionar la tabla EMPLEADO - OFERTA
ALTER TABLE OFERTA
ADD CONSTRAINT EMPLEADO_OFERTA_IDEMP
FOREIGN KEY (IDEMP) REFERENCES EMPLEADO (IDEMP);

-- Relacionar la tabla OFERTA - INSCRIPCION
ALTER TABLE INSCRIPCION
ADD CONSTRAINT OFERTA_INSCRIPCION_IDOFER
FOREIGN KEY (IDOFER) REFERENCES OFERTA (IDOFER);

-- Relacionar la tabla CURSO - OFERTA
ALTER TABLE OFERTA
ADD CONSTRAINT CURSO_OFERTA_CODCUR
FOREIGN KEY (CODCUR) REFERENCES CURSO (CODCUR);

-- Listar relaciones entre tablas
SELECT * 
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
WHERE table_schema="dbCursos" 
    AND constraint_type="FOREIGN KEY";
